#!/bin/bash
# https://askubuntu.com/questions/648603/how-to-create-an-animated-gif-from-mp4-video-via-command-line
ffmpeg -i $1 -r 30 -vf "scale=$2:-1,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" ${1%.*}.gif
